CREATE DATABASE IF NOT EXISTS oasisCMS;
USE oasisCMS;

CREATE TABLE MEMBER (
	MEMBER_NO		BIGINT	PRIMARY KEY,
    MEMBER_ID 		VARCHAR(100) NOT NULL, UNIQUE,
	PASSWD			VARCHAR(100) NOT NULL,
	JOIN_DT			TIMESTAMP	DEFAULT NOW(),
	MEMBER_NM 		VARCHAR(50)	NOT NULL,
	MEMBER_NK		VARCHAR(50)	NOT NULL,
	PROFILE_IMG 	VARCHAR(200),
	PROFILE_UUID	VARCHAR(200),
	SEX 			VARCHAR(1)		DEFAULT 'M',
	HP 				VARCHAR(20),
	EMAIL			VARCHAR(50),
	ZIPCODE 		VARCHAR(10),
	ROAD_ADDRESS 	VARCHAR(20),
	JIBUN_ADDRESS 	VARCHAR(50),
	NAMUJI_ADDRESS 	VARCHAR(50),
	ETC				VARCHAR(200),
	ACTIVE_YN		VARCHAR(1) DEFAULT 'Y',
	INACTIVE_DT		TIMESTAMP,
	LOGIN_YN		CHAR(1) DEFAULT 'N',
	LOGIN_DT		TIMESTAMP

);