CREATE DATABASE IF NOT EXISTS oasisCMS;
USE oasisCMS;

CREATE TABLE BS (
	BS_ID BIGINT PRIMARY KEY,
    BS_TITLE VARCHAR(100) NOT NULL,
    BS_IMG VARCHAR(100) DEFAULT "BS_IMG.JPG",
    BS_UUID VARCHAR(100),
    BS_READ_CNT BIGINT,
    BS_CATEGORY_1 VARCHAR(100) NOT NULL,
    BS_CATEGORY_2 VARCHAR(100),
    BS_CATEGORY_3 VARCHAR(100)
);